#!/bin/bash

set -e

DOTFILES_DIR="${HOME}/etc/dotfiles"
readonly DOTFILES_DIR

REMOTE_URL='git@github.com:anttikivi/dotfiles.git'
readonly REMOTE_URL

echo "Running the dotfiles bootstrapping script!"

echo "Checking if the dotfiles repository is present at ${DOTFILES_DIR}"

if [ ! -e "${DOTFILES_DIR}" ]; then
  echo "Cloning the dotfiles repository into ${DOTFILES_DIR}"
  git clone "${REMOTE_URL}" "${DOTFILES_DIR}"
fi

cd "${DOTFILES_DIR}"

echo "Running the main script"

./install

cd - >/dev/null

echo "Bootstrapping complete!"

echo "You probably need to launch a new shell to properly enjoy the experience that was set up"
