#!/bin/bash

set -e

ETC_DIR="${HOME}/etc"
readonly ETC_DIR
DOTFILES_DIR="${ETC_DIR}/dotfiles"
readonly DOTFILES_DIR
HTTPS_REMOTE_URL='https://github.com/anttikivi/dotfiles.git'
readonly HTTPS_REMOTE_URL
SSH_REMOTE_URL='git@github.com:anttikivi/dotfiles.git'
readonly SSH_REMOTE_URL
PURUS_HTTPS_URL='https://github.com/anttikivi/purus.git'
readonly PURUS_HTTPS_URL
PURUS_SSH_URL='git@github.com:anttikivi/purus.git'
readonly PURUS_SSH_URL

echo "Running the dotfiles bootstrapping script!"

echo "Checking if the dotfiles repository is present at ${DOTFILES_DIR}"

first_run="false"

if [ ! -e "${DOTFILES_DIR}" ]; then
  first_run="true"
  if [ ! -d "${ETC_DIR}" ]; then
    mkdir "${ETC_DIR}"
  fi
  echo "Cloning the dotfiles repository into ${DOTFILES_DIR}"
  git clone "${HTTPS_REMOTE_URL}" "${DOTFILES_DIR}"
elif [ "$(git -C "${DOTFILES_DIR}" remote get-url origin)" != "${SSH_REMOTE_URL}" ]; then
  first_run="true"
fi

if [ "${first_run}" = "true" ]; then
  echo "This is marked as the first run"
fi

cd "${DOTFILES_DIR}"

if [ "${first_run}" = "true" ]; then
  echo "Changing the URL for the 'purus' submodule"
  git submodule set-url -- purus "${PURUS_HTTPS_URL}"
fi

echo "Running the main script"

if [ "${first_run}" = "true" ]; then
  FIRST_RUN=true ./install
else
  ./install
fi

# shellcheck source=../../.bash_profile
source ~/.bash_profile

if [ "${first_run}" = "true" ]; then
  echo "Changing the URL for the 'purus' submodule back to the original"
  git submodule set-url -- purus "${PURUS_SSH_URL}"
  echo "Updating the submodules"
  git submodule sync --recursive
  git submodule update --init --recursive
  echo "Checking the remote URL of the dotfiles repository"
  current_url="$(git remote get-url origin)"
  echo "The remote URL of the dotfiles repository is currently set to ${current_url}"

  if [ "${current_url}" != "${SSH_REMOTE_URL}" ]; then
    git remote set-url origin "${SSH_REMOTE_URL}"
  fi

  echo "The remote URLs of the dotfiles repository are now set to:"
  git remote -v
fi

cd - >/dev/null

echo "Bootstrapping complete!"

echo "You probably need to launch a new shell to properly enjoy the experience that was set up"
