#!/bin/sh

# shellcheck disable=SC2034
CATPPUCCIN_NAME="catppuccin"

CATPPUCCIN_FRAPPE="frappe"
CATPPUCCIN_MACCHIATO="macchiato"
CATPPUCCIN_MOCHA="mocha"
CATPPUCCIN_LATTE="latte"

ROSE_PINE_NAME="rose-pine"
ROSE_PINE_MAIN="main"
ROSE_PINE_MOON="moon"
ROSE_PINE_DAWN="dawn"
KITTY_ROSE_PINE_NAME="Rosé Pine"
KITTY_ROSE_PINE_MOON="Moon"
KITTY_ROSE_PINE_DAWN="Dawn"

export COLOR_SCHEME="${ROSE_PINE_NAME}"
export COLOR_SCHEME_DARK_VARIANT="${ROSE_PINE_MAIN}"
export COLOR_SCHEME_LIGHT_VARIANT="${ROSE_PINE_DAWN}"
export DARK_COLOR_SCHEME="${ROSE_PINE_NAME}"
export LIGHT_COLOR_SCHEME="${ROSE_PINE_NAME}-${ROSE_PINE_DAWN}"
export KITTY_DARK_COLOR_SCHEME="${KITTY_ROSE_PINE_NAME}"
export KITTY_LIGHT_COLOR_SCHEME="${KITTY_ROSE_PINE_NAME} ${KITTY_ROSE_PINE_DAWN}"
