# shellcheck disable=SC2034
readonly CATPPUCCIN_NAME="catppuccin"

readonly CATPPUCCIN_FRAPPE="frappe"
readonly CATPPUCCIN_MACCHIATO="macchiato"
readonly CATPPUCCIN_MOCHA="mocha"
readonly CATPPUCCIN_LATTE="latte"

readonly ROSE_PINE_NAME="rose-pine"
readonly ROSE_PINE_MAIN="main"
readonly ROSE_PINE_MOON="moon"
readonly ROSE_PINE_DAWN="dawn"
readonly KITTY_ROSE_PINE_NAME="Rosé Pine"
readonly KITTY_ROSE_PINE_MOON="Moon"
readonly KITTY_ROSE_PINE_DAWN="Dawn"

export COLOR_SCHEME="${ROSE_PINE_NAME}"
export COLOR_SCHEME_DARK_VARIANT="${ROSE_PINE_MAIN}"
export COLOR_SCHEME_LIGHT_VARIANT="${ROSE_PINE_DAWN}"
export DARK_COLOR_SCHEME="${ROSE_PINE_NAME}"
export LIGHT_COLOR_SCHEME="${ROSE_PINE_NAME}-${ROSE_PINE_DAWN}"
export KITTY_DARK_COLOR_SCHEME="${KITTY_ROSE_PINE_NAME}"
export KITTY_LIGHT_COLOR_SCHEME="${KITTY_ROSE_PINE_NAME} ${KITTY_ROSE_PINE_DAWN}"
