#!/usr/bin/env bash

set -e

source ./utils/colors.sh

HAS_CONNECTION=false

if ping -q -c1 8.8.8.8 &>/dev/null; then
  HAS_CONNECTION=true
fi

export HAS_CONNECTION

if [ "${DOTFILES_UPDATE}" = 1 ]; then
  echo -e "${DOTFILES_ESC_YELLOW}Installing updates if they are available${DOTFILES_ESC_RESET}"
  printf "\n"
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

printf "\n"
echo -e "${DOTFILES_ESC_BLUE}Starting the kitty tasks${DOTFILES_ESC_RESET}"
"${BASEDIR}/scripts/kitty.sh"
echo -e "${DOTFILES_ESC_GREEN}==> kitty tasks run${DOTFILES_ESC_RESET}"

printf "\n"
echo -e "${DOTFILES_ESC_BLUE}Starting the Neovim tasks${DOTFILES_ESC_RESET}"
"${BASEDIR}/scripts/nvim.sh"
echo -e "${DOTFILES_ESC_GREEN}==> Neovim tasks run${DOTFILES_ESC_RESET}"
