---
- name: Workstation configuration
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect the host user
      ansible.builtin.import_tasks: pre_tasks/user.yml
      tags:
        - always

  tasks:
    - name: Run the `common` role
      ansible.builtin.include_role:
        name: common
      tags: always

    - name: Set roles
      ansible.builtin.set_fact:
        run_roles:
          "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles
          | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
# vi: ft=yaml.ansible
