#!/bin/sh

set -e

not_supported() {
  echo "This system is not supported: $*" >&2
  exit 1
}

if [ "${HAS_CONNECTION}" != "true" ]; then
  echo "Skipping the AWS CLI tasks as there is no Internet connection"
  exit 0
fi

if command -v aws >/dev/null 2>&1 && [ "${DISABLE_UPDATES}" = "true" ]; then
  echo "AWS CLI is already installed and updates are disabled, skipping..."
  exit 0
fi

if [ "${OS_NAME}" = "darwin" ]; then
  echo "Starting to install or update the AWS CLI"
  tmp_dir="${HOME}/tmp/awscli"
  if [ ! -d "${tmp_dir}" ]; then
    mkdir "${tmp_dir}"
  fi
  echo "Created to temporary directory"
  pkg_file="${tmp_dir}/AWSCLIV2.pkg"
  choices_file="${tmp_dir}/aws_cli_choices.xml"
  if [ -f "${choices_file}" ]; then
    rm "${choices_file}"
  fi
  echo "Copying the AWS CLI installation choices file to ${choices_file}"
  cp ../templates/aws_cli_choices.xml "${choices_file}"
  # TODO: Think about setting the `--silent` flag (or rather `-sS`).
  # shellcheck disable=SC2046
  curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "${pkg_file}"
  echo "Downloaded the AWS CLI installer package"
  installer -pkg "${pkg_file}" -target CurrentUserHomeDirectory -applyChoiceChangesXML "${choices_file}"
  rm "${choices_file}"
  echo "Ran the AWS CLI installer"
  if [ -e ~/.local/bin/aws ]; then
    rm ~/.local/bin/aws
  fi
  if [ -e ~/.local/bin/aws_completer ]; then
    rm ~/.local/bin/aws_completer
  fi
  echo "Removed the old symlinks"
  ln -s ~/.local/opt/aws-cli/aws ~/.local/bin/aws
  ln -s ~/.local/opt/aws-cli/aws_completer ~/.local/bin/aws_completer
  echo "Created new symlinks"
  rm -rf "${tmp_dir}"
  echo "Removed the temporary files"
  echo "Installed or updated the AWS CLI"
else
  not_supported "${OS_NAME}"
fi
