#!/bin/sh

set -e

\. ../directories.sh

not_supported() {
  echo "This system is not supported: $*" >&2
  exit 1
}

if [ "${HAS_CONNECTION}" != "true" ]; then
  echo "Skipping the Google Cloud CLI tasks as there is no Internet connection"
  exit 0
fi

if [ "${OS_NAME}" = "darwin" ]; then
  if ! command -v gcloud >/dev/null 2>&1; then
    echo "Starting to install the Google Cloud CLI"
    gcloud_dir="${LOCAL_OPT_DIR}/google-cloud-sdk"
    if [ -d "${gcloud_dir}" ]; then
      rm -rf "${gcloud_dir}"
    fi
    curl -LsS "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-darwin-arm.tar.gz" | tar -xzf - -C "$(dirname "${gcloud_dir}")"
  elif [ "${DISABLE_UPDATES}" != "true" ]; then
    gcloud components update
  fi
else
  not_supported "${OS_NAME}"
fi
