#!/bin/bash

set -e

source ../utils/colors.sh

if [ "${HAS_CONNECTION}" = "true" ]; then
  echo "Installing brunch.nvim"

  brunch_dir="${HOME}/development/plugins/brunch.nvim"
  brunch_repo="git@github.com:anttikivi/brunch.nvim.git"

  if [ ! -d "${brunch_dir}" ]; then
    git clone "${brunch_repo}" "${brunch_dir}"
  fi
fi
