#!/bin/sh

set -e

if [ "${HAS_CONNECTION}" != "true" ]; then
  echo "Skipping the Rust tasks as there is no Internet connection"
  exit 0
fi

if ! command -v rustc >/dev/null 2>&1; then
  echo "Installing the Rust toolchain"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y
elif [ "${DISABLE_UPDATES}" != "true" ]; then
  echo "Updating the Rust toolchain"
  rustup update
else
  echo "Not installing Rust"
fi
