#!/bin/sh

set -e

if [ "${HAS_CONNECTION}" != "true" ]; then
  echo "Skipping the TOML tasks as there is no Internet connection"
  exit 0
fi

if ! command -v taplo >/dev/null 2>&1; then
  echo "Installing Taplo"
  os="$(uname | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  if [ "${arch}" = "arm64" ]; then
    arch="aarch64"
  fi
  tmp_file="${HOME}/taplo-full-${os}-${arch}"
  if [ -f "${tmp_file}" ]; then
    echo "The temporary file already exists at ${tmp_file}, removing..."
    rm "${tmp_file}"
  fi
  echo "Downloading Taplo to ${tmp_file}"
  curl -fsSL "https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-${os}-${arch}.gz" | gzip -d - >"${tmp_file}"
  echo "Installing Taplo"
  install -m 0755 "${tmp_file}" ~/.local/bin/taplo
  echo "Removing the temporary file at ${tmp_file}"
  rm "${tmp_file}"
fi
