#!/usr/bin/env sh

# Overwrite for a space with the `--space 0` option
yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

# Set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl

# Set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# Set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m rule --add app="^System Settings$" manage=off
