export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$HOME"

export SHARED_ENV_DIR="$XDG_CONFIG_HOME/env"

for file in $XDG_CONFIG_HOME/env/*; do
  # The Google Cloud file modifies path and, thus, it is sourced in `.zshrc`.
  test "$file" = $XDG_CONFIG_HOME/env/gcloud && continue
  source $file
done
unset file

export NVM_DIR="$HOME/.nvm"

export CC="clang"
export CXX="clang++"
