# Source the environment variables populated by Ansible.
source $HOME/.env_from_ansible

# Source the secrets.
source $HOME/.env_secrets

# Source the colors scheme environment variables.
source $HOME/.config/colors.sh

# Set up local binaries and scripts.
export PATH="$HOME/.local/bin:$PATH"

# Set up the Homebrew shell environment.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Set up Alacritty.
export PATH="/Applications/Alacritty.app/Contents/MacOS:$PATH"

# Set up Go.
# TODO: Change the GOPATH.
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"

# Set up Python.
export PATH="$(brew --prefix python)/libexec/bin:$PATH"
export PYTHONPATH="$(brew --prefix)/lib/python$(python --version | awk '{print $2}' | cut -d '.' -f 1,2)/site-packages"

# Set up Rust.
source "$HOME/.cargo/env"

# Set up PHP.
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Set up nvm.
export NVM_DIR="$HOME/.nvm"
