export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$HOME"

export SHARED_ENV_DIR="$XDG_CONFIG_HOME/env"

for file in $XDG_CONFIG_HOME/env/*; do
  source $file
done
unset file

export GOPATH="$HOME/.local/go"
export GOBIN="$GOPATH/bin"

export NVM_DIR="$HOME/.nvm"

export CC="clang"
export CXX="clang++"
