fpath+=($HOME/.zsh/pure)

autoload -U promptinit
promptinit

zstyle ':prompt:pure:prompt:success' color white

prompt pure

autoload -U +X compinit
compinit

autoload -U +X bashcompinit
bashcompinit

export MANPAGER='nvim +Man!'

if [ -f "$XDG_CONFIG_HOME/env/colors" ]; then
  source $XDG_CONFIG_HOME/env/colors
fi

# The Zsh options for reference:
# https://zsh.sourceforge.io/Doc/Release/Options.html
for file in $DOTFILES_DIR/zsh/*.zsh; do
  source "$file"
done
unset file
