fpath+=($HOME/.zsh/pure)

autoload -U promptinit
promptinit

zstyle ':prompt:pure:prompt:success' color white

prompt pure

autoload -Uz compinit
compinit

autoload -Uz bashcompinit
bashcompinit

export MANPAGER='nvim +Man!'

export PATH="$HOME/.local/bin:$PATH"
export PATH="/Applications/Alacritty.app/Contents/MacOS:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$(brew --prefix python)/libexec/bin:$PATH"

for file in $DOTFILES_DIR/zsh/*.zsh; do
  source "$file"
done
