#!/bin/sh

set -e

readonly ESC="\033"
readonly ESC_RESET="${ESC}[0m"
readonly ESC_UNDERLINE="${ESC}[4m"

readonly ESC_RED="${ESC}[31m"
readonly ESC_GREEN="${ESC}[32m"
readonly ESC_YELLOW="${ESC}[33m"
readonly ESC_BLUE="${ESC}[34m"
readonly ESC_MAGENTA="${ESC}[35m"

readonly CHAR_CHECK_MARK="${ESC_BOLD}${ESC_GREEN}\xE2\x9C\x94${ESC_RESET}"
readonly CHAR_X_MARK="${ESC_BOLD}${ESC_RED}\xE2\x9C\x96${ESC_RESET}"

readonly DOTFILES_DIR="${HOME}/.dotfiles_tmp"

darwin() {
  if ! command -v brew >/dev/null 2>&1; then
    printf "Homebrew not found!\n"
  else
    printf "${CHAR_X_MARK} ${ESC_RED}Uninstalling ${ESC_BOLD}Homebrew${ESC_RESET}${ESC_RED}...${ESC_RESET}\n"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

    # Homebrew leaves behind some directories we need to delete ourselves.
    rm -rf /opt/homebrew/Frameworks/
    rm -rf /opt/homebrew/bin/
    rm -rf /opt/homebrew/etc/
    rm -rf /opt/homebrew/include/
    rm -rf /opt/homebrew/lib/
    rm -rf /opt/homebrew/opt/
    rm -rf /opt/homebrew/sbin/
    rm -rf /opt/homebrew/share/
    rm -rf /opt/homebrew/var/

    printf "${CHAR_CHECK_MARK} ${ESC_YELLOW}Homebrew uninstalled!${ESC_RESET}\n"
  fi

  stty -echo
  printf "Password: "
  read password
  stty echo
  printf "\n"

  printf "${CHAR_X_MARK} ${ESC_RED}Uninstalling configuration files and temporary files created by programs...${ESC_RESET}\n"

  rm -rf "${HOME}/.ansible"
  rm -rf "${HOME}/.aws"
  rm -rf "${DOTFILES_DIR}"
  rm -rf "${HOME}/.cache"
  rm -rf "${HOME}/.cargo"
  rm -rf "${HOME}/.composer"
  rm -rf "${HOME}/.config"
  rm -rf "${HOME}/.local"
  rm -rf "${HOME}/.npm"
  rm -rf "${HOME}/.nvm"
  rm -rf "${HOME}/.oh-my-zsh"
  rm -rf "${HOME}/.rustup"
  rm -rf "${HOME}/.ssh"
  rm -rf "${HOME}/.terraform.d"
  rm -rf "${HOME}/.zsh_sessions"
  echo "${password}" | sudo -S rm -rf "${HOME}/go"
  rm -rf "${HOME}/tools"

  rm -f "${HOME}/.gitconfig"
  rm -f "${HOME}/.gitignore_global"
  rm -f "${HOME}/.tmux.conf"
  find . -type f -name ".zcompdump-*" -maxdepth 1 -exec rm -f {} \;
  rm -f "${HOME}/.zsh_history"
  rm -f "${HOME}/.zshrc"

  echo "${password}" | sudo -S rm -rf "/usr/local/go"

  printf "${CHAR_CHECK_MARK} ${ESC_YELLOW}Configuration files and temporary files uninstalled!${ESC_RESET}\n" "" "" ""
}

not_supported() {
  printf "${CHAR_X_MARK} ${ESC_BOLD}${ESC_RED}This operating system is not supported!${ESC_RESET}\n"
  exit 1
}

printf "${ESC_BOLD}${ESC_BLUE}Running the environment uninstallation...${ESC_RESET}\n"

old_pwd="$(pwd)"
cd "${HOME}"

os_name="$(uname)"
printf "${CHAR_CHECK_MARK} Running on ${ESC_UNDERLINE}${os_name}${ESC_RESET}\n"
if [ "${os_name}" = "Darwin" ]; then
  darwin
else
  not_supported
fi

cd "${old_pwd}"

printf "${ESC_BOLD}${ESC_MAGENTA}Finished the environment uninstallation!${ESC_RESET}\n"
